
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[539] =
    {   0,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,   95,   93,    2,    1,    2,   92,   91,   91,
       91,   93,   92,   93,   93,   93,   84,    3,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,    2,   89,   93,   93,   93,    2,    2,   92,
        0,   92,    0,    0,   21,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   92,    0,   19,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    2,   89,    0,    0,    0,   90,   26,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   66,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   60,    0,    0,    0,   42,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   27,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   92,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   80,    0,    0,    0,    6,    0,    0,    5,    0,
       22,   67,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   61,    0,    0,
       43,    0,    0,    0,    0,    0,    0,    0,    0,   28,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   41,    0,   58,    0,   50,   52,   68,    0,    0,
       13,   23,   25,   29,    0,    0,   79,   48,   44,    0,

        0,    0,    0,    0,   35,   33,    0,   31,   74,   46,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   92,   83,   17,    0,    0,
       16,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   59,    0,   51,   53,   69,    0,    0,   14,   24,
       30,    0,    0,   49,   45,    0,    0,    0,    0,    0,
       36,   34,   32,   75,   47,    0,    0,    0,    0,    0,
        0,   26,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   76,    0,    0,   15,    0,    0,    0,    0,
       54,   56,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   92,   20,    0,   81,    0,
        0,    0,    0,    0,    0,    0,   77,    0,    0,    0,
        0,    0,    0,    0,   55,   57,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   10,
        0,    0,    0,    9,    7,    0,    0,   85,    0,    0,
        0,    0,    0,    0,    0,    0,   92,   82,   86,    0,
       87,    0,    0,    0,    0,   18,   88,    8,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   62,    0,   11,    0,    0,    0,    0,    0,
       37,    0,    0,    0,    0,    0,   63,    0,   78,    0,

        0,    0,    0,    0,   12,   39,    0,   70,   64,    0,
        0,    0,    0,   40,    0,   71,   65,    0,    0,    0,
       37,    0,    0,    4,   38,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   72,   73,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    7,    7,    8,    9,   10,
       10,   10,   10,   10,   11,   10,   12,   13,   14,   15,
       16,   17,   13,   13,   13,   13,   13,   10,   18,   19,
       20,   21,   10,   10,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   31,   32,   33,   34,   35,   36,
       31,   37,   38,   39,   40,   41,   42,   31,   43,   44,
        1,    7,    1,    7,    7,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   31,   31,   54,   55,   56,
       57,   58,   31,   59,   60,   61,   62,   63,   64,   31,
       65,   66,    7,    1,    7,    7,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[67] =
    {   0,
        1,    2,    3,    4,    4,    5,    6,    6,    7,    4,
        8,    4,    4,    4,    4,    4,    4,    4,    6,    4,
        6,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9
    } ;

static yyconst flex_uint16_t yy_base[548] =
    {   0,
        0,   24,   47,  107,   23,   35,  150,  196,   12,   36,
       78,  106,  765,  766,    7,  766,   16,  762,  766,    0,
        4,  256,    8,  757,  753,    8,  766,  766,  724,  738,
      729,  699,  712,  703,  725,  701,  727,  715,  721,  701,
      690,  695,   40,  745,  735,  710,  687,   61,   68,  741,
      724,   39,   35,  297,  766,   57,  715,  112,  707,   24,
      139,    1,  709,  706,  716,   49,  161,   72,   64,   53,
      151,  681,   61,  133,   50,  682,  680,  712,  109,  168,
       79,  130,  726,  766,  722,  695,  672,  702,  694,  687,
      676,  669,  662,  678,  655,  690,  695,  693,  664,  669,

      667,  118,  712,  692,  675,  652,  766,  708,  698,  673,
      686,  122,   93,  192,  673,  142,  225,  684,  674,  671,
      681,  141,  233,  155,  680,  139,  148,  193,  645,  150,
      324,  678,  645,  643,  675,  171,  308,  154,  766,  670,
      197,  660,  672,  651,  670,  669,  668,  660,  653,  665,
      664,  663,  662,  660,  648,  766,  652,  658,  657,  766,
      655,  639,   54,  652,  653,  652,  633,  650,  649,  766,
      648,  620,  207,  609,  610,  644,  601,  642,  641,  640,
      609,  603,  637,  636,  635,  634,  609,  598,  601,  630,
      629,  604,  589,  115,  601,  625,  624,  583,  622,  621,

      620,  234,  613,  613,  606,  587,  587,  581,  608,  584,
      604,  766,  592,  579,  568,  766,  603,  579,  766,  602,
      766,  766,  600,  588,  589,  601,  580,  599,  598,  597,
      589,  582,  594,  593,  592,  590,  578,  766,  589,  588,
      766,  586,  570,  214,  583,  584,  583,  582,  581,  766,
      580,  552,  541,  542,  576,  533,  574,  573,  572,  541,
      535,  569,  568,  567,  566,  541,  530,  563,  562,  537,
      522,  207,  534,  558,  557,  516,  555,  554,  553,  530,
      551,  766,  532,  766,  549,  766,  766,  766,  161,  530,
      766,  766,  766,  766,  543,  535,  766,  766,  766,  534,

      530,  543,  542,  530,  766,  766,  529,  766,  766,  766,
      495,  538,  497,  496,  535,  197,  494,  506,  499,  498,
      494,  529,  528,  494,  493,  193,  766,  766,  520,  496,
      766,  515,  514,  490,  489,  514,  490,  499,  494,  497,
      496,  766,  513,  766,  766,  766,  247,  494,  766,  766,
      766,  507,  499,  766,  766,  498,  494,  507,  506,  494,
      766,  766,  766,  766,  766,  460,  463,  462,  501,  222,
      460,  766,  472,  465,  464,  460,  495,  494,  460,  459,
      491,  485,  766,  488,  472,  766,  487,  486,  474,  471,
      766,  766,  478,  477,  481,  448,  451,  454,  439,  476,

      475,  441,  438,  444,  443,  241,  766,  452,  766,  429,
      452,  429,  444,  465,  455,  458,  766,  461,  445,  460,
      459,  458,  446,  443,  766,  766,  450,  454,  421,  424,
      427,  412,  449,  448,  447,  413,  410,  416,  415,  766,
      426,  426,  435,  766,  766,  439,  431,  766,  437,  400,
      397,  397,  405,  432,  401,  430,  104,  766,  766,  414,
      766,  408,  402,  398,  405,  766,  766,  766,  407,  397,
      403,  360,  355,  326,  334,  361,  330,  359,  358,  357,
      338,  355,  766,  354,  766,  318,  351,  310,  349,  347,
      364,  339,  330,  342,  323,  331,  766,  327,  766,  278,

      310,  269,  307,  304,  766,  766,  285,  766,  766,  291,
      258,  286,  279,  766,  269,  766,  766,  277,  244,  258,
      766,  233,  268,  256,  766,  240,  217,  233,  210,  229,
      193,  224,  110,   59,    8,  766,  766,  766,  385,  394,
      403,  411,    8,  417,  423,  431,  440
    } ;

static yyconst flex_int16_t yy_def[548] =
    {   0,
      539,  539,  540,  540,    4,    4,    4,    4,  541,  541,
        4,    4,  538,  538,  538,  538,  542,  542,  538,  543,
      542,  538,  542,  544,  545,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  546,  546,  538,  538,  538,  538,  542,  542,
      543,  542,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  542,  544,  538,  545,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,

      538,  546,  546,  538,  538,  538,  538,  542,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,

      538,  542,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,

      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  542,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,

      538,  538,  538,  538,  538,  542,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  542,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      542,  538,  538,  538,  538,  538,  538,  538,  538,  538,

      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  547,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  547,  547,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,    0,  538,  538,
      538,  538,  538,  538,  538,  538,  538
    } ;

static yyconst flex_uint16_t yy_nxt[833] =
    {   0,
       14,   15,   16,   17,  538,  538,   19,   20,   48,  538,
       48,   21,   14,   15,   16,   43,   51,   48,   22,   49,
       14,  156,   45,   23,   14,   15,   16,   17,  537,   82,
       19,   20,   52,  157,   86,   21,   14,   15,   16,   43,
      538,   48,   22,  102,   14,  109,   45,   23,   15,   16,
       15,   14,   24,  148,  108,   25,   14,   87,  149,  110,
       35,   14,   48,   14,   48,   26,   27,   28,   14,   48,
      156,   49,   35,   14,   14,   29,  302,  139,   14,  537,
       30,  161,   36,   14,  139,   31,   14,  162,  163,  303,
       14,  140,  170,  141,   36,   14,   14,  174,   32,  170,

       46,  175,   33,  171,  189,  538,   14,   34,   15,   16,
       15,   14,   24,  181,  224,   25,   14,  182,  225,   48,
      172,  102,  173,   47,   14,   26,   27,   28,   46,   14,
      536,  538,  201,   14,   14,   29,  143,  491,   14,   14,
       30,  144,  222,  145,   14,   31,  183,  184,  185,  186,
      146,   47,  150,  151,  152,  153,  223,   14,   32,  222,
      322,   14,   33,  192,  154,  202,   14,   34,   14,  193,
      194,  231,  323,  242,  250,  250,  232,  155,   37,  243,
      244,  187,  164,   14,  384,  165,  251,   38,   14,  166,
      167,   39,  253,  188,  538,  252,  254,  168,  176,  169,

      385,   40,  260,  177,  178,   14,  261,  279,  281,   41,
       14,  179,  195,   42,   14,  196,  226,  282,  312,  197,
      198,  227,  406,  228,   37,  270,  199,  282,  200,   14,
      229,  271,  272,   38,   14,  538,  358,   39,  233,  234,
      255,  235,  538,  398,  536,  256,  257,   40,  535,  359,
      236,   14,  377,  258,  245,   41,   14,  246,  399,   42,
       53,  247,  534,  237,  378,  533,  532,   54,  431,  248,
      418,  249,  326,  531,  530,  457,  524,   55,   56,   57,
       58,   59,   60,  432,   61,   62,  419,   63,  524,  529,
       64,   65,  528,   66,   67,   68,  527,  525,  526,  525,

       55,   69,   70,   71,   72,   73,  524,   74,   75,   76,
      522,  521,   77,   78,  520,   79,   80,   81,  111,  112,
      113,  114,  115,  116,  517,  117,  118,  516,  119,  519,
      514,  120,  121,  518,  122,  123,  124,  262,  263,  264,
      265,  125,  126,  127,  128,  129,  130,  517,  131,  132,
      133,  516,  273,  134,  135,  274,  136,  137,  138,  275,
      276,  515,  514,  513,  512,  538,  277,  509,  278,  508,
      511,  506,  266,  510,  509,  508,  507,  506,  505,  499,
      504,  497,  503,  502,  267,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   14,   14,   14,   14,   14,   14,

       14,   14,   14,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   50,  501,   50,   50,  500,   50,   50,   50,
       83,   83,   83,  499,  498,   83,   85,  497,   85,   85,
      496,   85,  103,  495,  103,  103,  103,  103,  494,  103,
      523,  523,  493,  523,  523,  523,  523,  523,  523,  492,
      485,  490,  483,  489,  488,  487,  486,  485,  484,  483,
      482,  481,  480,  479,  478,  477,  476,  468,  467,  466,
      475,  474,  473,  472,  461,  471,  470,  469,  468,  467,
      466,  465,  464,  463,  462,  461,  460,  459,  459,  458,
      458,  456,  448,  455,  454,  445,  444,  453,  452,  451,

      450,  440,  449,  448,  447,  446,  445,  444,  443,  442,
      441,  440,  439,  438,  426,  425,  437,  436,  435,  434,
      433,  417,  430,  429,  428,  427,  426,  425,  424,  423,
      422,  421,  420,  417,  416,  415,  414,  413,  412,  411,
      409,  410,  409,  408,  407,  407,  405,  404,  392,  391,
      403,  402,  401,  400,  386,  383,  397,  396,  282,  395,
      394,  393,  392,  391,  390,  389,  388,  387,  386,  383,
      382,  282,  381,  365,  364,  363,  380,  362,  361,  379,
      376,  375,  355,  354,  374,  373,  351,  372,  350,  349,
      371,  370,  346,  345,  344,  369,  342,  368,  367,  366,

      365,  364,  363,  362,  361,  360,  357,  356,  355,  354,
      353,  352,  351,  350,  349,  348,  347,  346,  345,  344,
      343,  342,  341,  340,  339,  338,  337,  336,  335,  334,
      333,  332,  331,  331,  330,  328,  327,  329,  328,  327,
      310,  309,  308,  325,  306,  305,  324,  321,  320,  299,
      298,  297,  319,  318,  294,  293,  292,  291,  317,  316,
      288,  287,  286,  315,  284,  314,  313,  311,  310,  309,
      308,  307,  306,  305,  304,  301,  300,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  283,  280,  241,  269,  268,  238,  259,

      221,  241,  240,  239,  238,  230,  221,  220,  219,  538,
      218,  217,  216,  538,  215,  212,  214,  213,  212,  211,
      210,  209,  208,  207,  206,  205,  204,  203,  182,  149,
       84,   84,  160,  191,  190,  180,  160,  159,  158,  147,
      142,  107,  538,  106,  105,  104,  538,  101,  100,   99,
       98,   97,   96,   95,   94,   93,   92,   91,   90,   89,
       88,   84,   84,  538,  538,   13,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,

      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538
    } ;

static yyconst flex_int16_t yy_chk[833] =
    {   0,
        1,    1,    1,    1,    0,   21,    1,    1,   15,   23,
       15,    1,    9,    9,    9,    9,  543,   17,    1,   17,
        1,   62,    9,    1,    2,    2,    2,    2,  535,   23,
        2,    2,   21,   62,   26,    2,   10,   10,   10,   10,
       52,   43,    2,   43,    2,   53,   10,    2,    3,    3,
        3,    5,    3,   60,   52,    3,    5,   26,   60,   53,
        5,    5,   48,    6,   48,    3,    3,    3,    6,   49,
       75,   49,    6,    6,    5,    3,  163,   56,    5,  534,
        3,   66,    5,    5,   69,    3,    6,   66,   66,  163,
        6,   56,   68,   56,    6,    6,   11,   70,    3,   81,

       11,   70,    3,   68,   75,  457,   11,    3,    4,    4,
        4,   11,    4,   73,  113,    4,   11,   73,  113,  102,
       69,  102,   69,   11,   12,    4,    4,    4,   12,   11,
      533,   82,   81,   11,   12,    4,   58,  457,   11,   12,
        4,   58,  112,   58,   12,    4,   74,   74,   74,   74,
       58,   12,   61,   61,   61,   61,  112,   12,    4,  126,
      194,   12,    4,   79,   61,   82,   12,    4,    7,   79,
       79,  116,  194,  122,  138,  124,  116,   61,    7,  122,
      122,   74,   67,    7,  289,   67,  124,    7,    7,   67,
       67,    7,  127,   74,  326,  126,  127,   67,   71,   67,

      289,    7,  130,   71,   71,    7,  130,  138,  141,    7,
        7,   71,   80,    7,    8,   80,  114,  141,  173,   80,
       80,  114,  326,  114,    8,  136,   80,  173,   80,    8,
      114,  136,  136,    8,    8,  202,  244,    8,  117,  117,
      128,  117,  406,  316,  532,  128,  128,    8,  531,  244,
      117,    8,  272,  128,  123,    8,    8,  123,  316,    8,
       22,  123,  530,  117,  272,  529,  528,   22,  370,  123,
      347,  123,  202,  527,  526,  406,  524,   22,   22,   22,
       22,   22,   22,  370,   22,   22,  347,   22,  523,  522,
       22,   22,  520,   22,   22,   22,  519,  518,  515,  513,

       22,   22,   22,   22,   22,   22,  512,   22,   22,   22,
      511,  510,   22,   22,  507,   22,   22,   22,   54,   54,
       54,   54,   54,   54,  504,   54,   54,  503,   54,  502,
      501,   54,   54,  500,   54,   54,   54,  131,  131,  131,
      131,   54,   54,   54,   54,   54,   54,  498,   54,   54,
       54,  496,  137,   54,   54,  137,   54,   54,   54,  137,
      137,  495,  494,  493,  492,  491,  137,  490,  137,  489,
      488,  487,  131,  486,  484,  482,  481,  480,  479,  478,
      477,  476,  475,  474,  131,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  540,  540,  540,  540,  540,  540,

      540,  540,  540,  541,  541,  541,  541,  541,  541,  541,
      541,  541,  542,  473,  542,  542,  472,  542,  542,  542,
      544,  544,  544,  471,  470,  544,  545,  469,  545,  545,
      465,  545,  546,  464,  546,  546,  546,  546,  463,  546,
      547,  547,  462,  547,  547,  547,  547,  547,  547,  460,
      456,  455,  454,  453,  452,  451,  450,  449,  447,  446,
      443,  442,  441,  439,  438,  437,  436,  435,  434,  433,
      432,  431,  430,  429,  428,  427,  424,  423,  422,  421,
      420,  419,  418,  416,  415,  414,  413,  412,  411,  410,
      408,  405,  404,  403,  402,  401,  400,  399,  398,  397,

      396,  395,  394,  393,  390,  389,  388,  387,  385,  384,
      382,  381,  380,  379,  378,  377,  376,  375,  374,  373,
      371,  369,  368,  367,  366,  360,  359,  358,  357,  356,
      353,  352,  348,  343,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  330,  329,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  315,  314,  313,  312,  311,
      307,  304,  303,  302,  301,  300,  296,  295,  290,  285,
      283,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      271,  270,  269,  268,  267,  266,  265,  264,  263,  262,
      261,  260,  259,  258,  257,  256,  255,  254,  253,  252,

      251,  249,  248,  247,  246,  245,  243,  242,  240,  239,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  228,
      227,  226,  225,  224,  223,  220,  218,  217,  215,  214,
      213,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      201,  200,  199,  198,  197,  196,  195,  193,  192,  191,
      190,  189,  188,  187,  186,  185,  184,  183,  182,  181,
      180,  179,  178,  177,  176,  175,  174,  172,  171,  169,
      168,  167,  166,  165,  164,  162,  161,  159,  158,  157,
      155,  154,  153,  152,  151,  150,  149,  148,  147,  146,
      145,  144,  143,  142,  140,  135,  134,  133,  132,  129,

      125,  121,  120,  119,  118,  115,  111,  110,  109,  108,
      106,  105,  104,  103,  101,  100,   99,   98,   97,   96,
       95,   94,   93,   92,   91,   90,   89,   88,   87,   86,
       85,   83,   78,   77,   76,   72,   65,   64,   63,   59,
       57,   51,   50,   47,   46,   45,   44,   42,   41,   40,
       39,   38,   37,   36,   35,   34,   33,   32,   31,   30,
       29,   25,   24,   18,   13,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,

      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538,  538,  538,  538,  538,  538,  538,  538,  538,
      538,  538
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 5 "lexer.l"


#include<iostream>
#include<string>
#include<cstring>
#include "as.tab.h"
#include "AST.h"
using namespace std;


 






#line 850 "lex.yy.c"

#define INITIAL 0
#define A 1
#define FONTS 2
#define IMAGES 3
#define COMMENT 4
#define TABLE 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 35 "lexer.l"


#line 1076 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 539 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 766 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 37 "lexer.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 39 "lexer.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 41 "lexer.l"
{
				BEGIN(INITIAL);
				return E_ANG_BRACKET;
				}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 48 "lexer.l"
;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 51 "lexer.l"
{BEGIN(COMMENT);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 53 "lexer.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 56 "lexer.l"
{return S_HTML;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 58 "lexer.l"
{return E_HTML;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 "lexer.l"
{return S_HEAD;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 63 "lexer.l"
{return S_BODY;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 65 "lexer.l"
{return S_TITLE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 67 "lexer.l"
{return E_TITLE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 69 "lexer.l"
{ return S_H1;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 71 "lexer.l"
{return E_H1;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 73 "lexer.l"
{BEGIN(FONTS); 
				return FONT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 77 "lexer.l"
{return SIZE;
			}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 80 "lexer.l"
{return NAME;
			}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 83 "lexer.l"
{return E_FONT;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 85 "lexer.l"
{  char *temp = strdup(yytext);
						temp[strlen(temp)-1]='\0';
						temp++;						
						yylval.s = temp;
						return ATTR_VAL;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 92 "lexer.l"
{return TITLE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 93 "lexer.l"
{ BEGIN(A);
			return A_HREF;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 96 "lexer.l"
{ return E_A;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 98 "lexer.l"
{ return S_H2;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 100 "lexer.l"
{return E_H2;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 102 "lexer.l"
{return S_H3;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 104 "lexer.l"
{return E_H3;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 106 "lexer.l"
{return S_U;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 108 "lexer.l"
{return E_U;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 110 "lexer.l"
{return S_H4;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 112 "lexer.l"
{return E_H4;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 114 "lexer.l"
{return S_TR;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 116 "lexer.l"
{return E_TR;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 118 "lexer.l"
{return S_TH;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 120 "lexer.l"
{ return E_TH; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 122 "lexer.l"
{return S_TD; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 124 "lexer.l"
{return E_TD; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 126 "lexer.l"
{return S_CAPTION; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 128 "lexer.l"
{return E_CAPTION; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 130 "lexer.l"
{return S_CENTER; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 132 "lexer.l"
{return E_CENTER; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 134 "lexer.l"
{
				return BREAK; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 137 "lexer.l"
{return S_PARA; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 139 "lexer.l"
{return E_PARA; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 141 "lexer.l"
{return S_OLIST; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 143 "lexer.l"
{return E_OLIST; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 145 "lexer.l"
{return S_ULIST; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 147 "lexer.l"
{return E_ULIST; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 149 "lexer.l"
{return S_ITEM; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 151 "lexer.l"
{return E_ITEM; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 153 "lexer.l"
{return S_DL; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 155 "lexer.l"
{return E_DL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 157 "lexer.l"
{return S_DT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 159 "lexer.l"
{return E_DT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 161 "lexer.l"
{return S_SUB; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 163 "lexer.l"
{return E_SUB; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 165 "lexer.l"
{return S_SUP; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 167 "lexer.l"
{return E_SUP; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 169 "lexer.l"
{return S_DD; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 171 "lexer.l"
{return E_DD; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 173 "lexer.l"
{return S_I; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 174 "lexer.l"
{return E_I; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 176 "lexer.l"
{return S_SMALL; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 177 "lexer.l"
{return E_SMALL; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 179 "lexer.l"
{return S_STRONG; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 180 "lexer.l"
{return E_STRONG; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 182 "lexer.l"
{return S_BOLD; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 183 "lexer.l"
{return E_BOLD; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 185 "lexer.l"
{return S_EM; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 186 "lexer.l"
{return E_EM; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 188 "lexer.l"
{return S_FIG; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 189 "lexer.l"
{return E_FIG; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 191 "lexer.l"
{return S_FIGCAPTION; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 192 "lexer.l"
{return E_FIGCAPTION; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 194 "lexer.l"
{return S_TT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 195 "lexer.l"
{ return E_TT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 197 "lexer.l"
{return S_DIV; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 198 "lexer.l"
{return E_DIV; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 201 "lexer.l"
{return E_TABLE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 204 "lexer.l"
{ BEGIN(IMAGES);
				return IMAGE_WITH_ATTRIBUTE;  }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 207 "lexer.l"
{ return SOURCE; 
					}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 210 "lexer.l"
{return WIDTH ; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 212 "lexer.l"
{return HEIGHT; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 214 "lexer.l"
{ return HREF;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 216 "lexer.l"
;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 218 "lexer.l"
{BEGIN(TABLE);
				      return S_TABLE ; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 221 "lexer.l"
{return BORDER ; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 224 "lexer.l"
{return E_BODY; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 226 "lexer.l"
{return E_HEAD;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 230 "lexer.l"
; 
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 233 "lexer.l"
{char *temp = strdup(yytext);
			temp[strlen(temp)-1]='\0';
			temp++;	
			string str = map_greek$(string(temp));				
			char cstr[str.size() + 1];
	                strcpy(cstr, str.c_str());
			yylval.s = cstr;
			return STRING;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 243 "lexer.l"
{ char *temp= strdup(yytext);
				string str = map_symbol$(string(temp));
								
				char cstr[str.size() + 1];
	                	strcpy(cstr, str.c_str());
				yylval.s = strdup(cstr);
				//cout<<cstr<<"SYMBOL"<<endl;
				return STRING;
				}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 253 "lexer.l"
{
				yylval.s = strdup(yytext);
				return STRING; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 257 "lexer.l"
;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 259 "lexer.l"
ECHO;
	YY_BREAK
#line 1636 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(A):
case YY_STATE_EOF(FONTS):
case YY_STATE_EOF(IMAGES):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(TABLE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 539 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 539 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 538);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 259 "lexer.l"








/*
int main(int argc, char* argv[])
{
	if(argc > 1)
	{
		FILE *fp = fopen(argv[1], "r");

		if(fp)
			yyin = fp;
	}
	do {
		yylex();
	} while (!feof(yyin));
	return 1;}
*/

	

